name: crucible-merged

on:
  pull_request_target:
    types: [ closed ]
    branches: [ main ]
    paths-ignore:
      - LICENSE
      - '**.md'
      - .github/workflows/run-crucible-tracking.yaml
      - .github/workflows/faux-crucible-ci.yaml
      - 'docs/**'
  workflow_dispatch:

jobs:
  call-benchmark-crucible-ci_if-merged:
    if: github.event.pull_request.merged == true
    uses: perftool-incubator/crucible-ci/.github/workflows/benchmark-crucible-ci.yaml@main
    with:
      ci_target: "cyclictest"
      ci_target_branch: "main"
      github_workspace: "$GITHUB_WORKSPACE"
    secrets:
      production_registry_auth: ${{ secrets.CRUCIBLE_PRODUCTION_ENGINES_REGISTRY_AUTH }}
      quay_oauth_token: ${{ secrets.CRUCIBLE_QUAYIO_OAUTH_TOKEN }}
